### ISSUE TITLE
Editor does not display if it is not initially visible

### ISSUE THREAD

**Issue by DrNiels** [PolymerVis/monaco-editor#1]
If the monaco-editor is not initially visible, e.g., as part of an iron-pages, it does not show if it becomes visible. Instead, the editor merely takes the space according to its style, but that remains empty.

Here's a code example that displays this:
```javascript
    <dom-module id="console-app">
      <template>
        <iron-pages selected="[[_selected]]">
          <span>Hello World!</span>
          <monaco-editor
              folding
              minimap
              name="editor"
              theme="vs-dark"
              language="javascript"></monaco-editor>
        </iron-pages>
        <paper-button on-tap="_switchPage">Switch</paper-button>
      </template>
      <script>
          class ConsoleApp extends Polymer.Element {

              static get is() {
                  return 'console-app';
              }

              static get properties() {
                  return {
                      _selected: {
                          type: Number,
                          value: 0
                      }
                  }
              }

              _switchPage() {
                  this.set('_selected', (this._selected + 1) % 2);
              }
          }

          customElements.define(ConsoleApp.is, ConsoleApp);
      </script>
    </dom-module>
```

The editor is not displayed initially as it does have index 1, not 0. When the page is switched, a white block appears, but no editor. On the other hand, if _selected is initialized with 1, the editor is shown and remains shown after switching back and forth.

**Comment by eterna2** [comment]
Kk. Give me some time to look at it. Thanks for the heads up.

**Comment by anandanand84** [comment]
I also faced similar issue, we need to call `editor.layout()` but currently it is not exposed in the editor proxy. I can create a pull request.

**Comment by DrNiels** [comment]
Thanks a lot! It works great now!

While working with the updated editor I already found another bug :) https://github.com/PolymerVis/monaco-editor/issues/3
