### ISSUE TITLE
Propagate click into the editor to outside

### ISSUE THREAD

**Issue by DrNiels** [PolymerVis/monaco-editor#7]
In my program, I use global event click listener, e.g., for closing context menus. Unfortunately, when I click into the editor, the listener does not trigger. I guess, the iframe "blocks" the event from propagating so far. Is it possible to somehow react to clicks on the editor?

**Comment by eterna2** [comment]
U need to separately add a listener in the iframe. As they are 2 separate documents.

A possible solution is create a listener in the iframe. And everytime the event triggers, post a message back to the main document, which in turn triggers a custom event.

**Comment by DrNiels** [comment]
That's just what I did. If you want to use this for your editor as well, just merge pull request #9
